MythicMobs-Item: "InspectorsSpyglass"
Leash-PlayerLeashed: "<green>Вы привязали игрока <player>!"
Leash-PlayerUnleashed: "<red>Игрок <player> был отвязан!"
CoreProtect-Radius: 10
CoreProtect-NoHistory: "<yellow>История отсутствует!"
CoreProtect-InventoryName: "[<page>/<maxpage>] Найденные улики"
CoreProtect-PageForward: "<i:false><white>Страница вперёд >"
CoreProtect-PageBack: "<i:false><white>< Страница назад"
CoreProtect-BlockDestroyed: "<i:false><white>[<entry>]</white> <red>- <material>"
CoreProtect-BlockPlaced: "<i:false><white>[<entry>]</white> <green>+ <material>"
CoreProtect-BlockModified: "<i:false><white>[<entry>]</white> <yellow>% <material>"
CoreProtect-EntityKilled: "<i:false><white>[<entry>]</white> <red>Сущность убита"
CoreProtect-EntryLore:
  - "<i:false><white>X: <x>, Y: <y>, Z: <z>"
  - "<i:false><green>Источник: <player>"
  - "<i:false><blue>Дата: <time>"