name: Java with Gradle

on:
  push:
    branches: [ master ]

env:
  REPO_NAME: "${{ github.event.repository.name }}"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Allow gradlew to execute
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.REPO_NAME }}-${{ env.BUILD_NUMBER }}"
          path: build/libs/*.jar